name: Deploy Shared Resources

on:
  workflow_dispatch:

env:
  # Place for environment variables
  RESOURCE_GROUP: 'container-apps-rg'
  LOCATION: 'eastus'
  # Add more environment variables as needed

jobs:
  deploy:
    name: Deploy Resources
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Azure Login
        uses: azure/login@v1.6.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Shared Resources
        uses: azure/arm-deploy@v2
        id: bicep-deploy
        with:
          scope: 'subscription'
          subscriptionId: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          template: 'env/shared/main.bicep'
          region: ${{ vars.LOCATION }}
          parameters: >
            resourceGroup=${{ vars.RESOURCE_GROUP }}
            location=${{ vars.LOCATION }}
            project=reporunners
          deploymentName: 'deploy-aca-runner-shared-infra'

      - name: Update GitHub variables
        run: |
          gh variable set PROJECT --body ${{ steps.bicep-deploy.outputs.project }}
          gh variable set ACA_MI_NAME --body ${{ steps.bicep-deploy.outputs.acaManagedIDName }}
          gh variable set ACR_NAME --body ${{ steps.bicep-deploy.outputs.acrName }}
          gh variable set ACA_ENV_NAME --body ${{ steps.bicep-deploy.outputs.acaEnvName }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - run : |
          az acr config authentication-as-arm show --registry ${{ steps.bicep-deploy.outputs.acrName }}
          az acr build -r ${{ steps.bicep-deploy.outputs.acrName }} -g ${{ vars.RESOURCE_GROUP }} -f src/Dockerfile.from-ghcr -t ${{ steps.bicep-deploy.outputs.project }}:latest src