name: Test self-hosted runners

on:
  workflow_dispatch:
    
jobs:
  test:
    runs-on: self-hosted

    steps:
      - run: |
          az login --identity -u $MSI_CLIENT_ID
          az account show
          az group list --query '[].name' -o tsv
        name: Execute az cli sample commands